apiVersion: v1
kind: Service
metadata:
  name: bin2dec-api
  labels:
    {{- include "bin2dec.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: bin2dec-api
    app.kubernetes.io/instance: {{ .Release.Name }}
