apiVersion: apps/v1
kind: Deployment
metadata:
  name: bin2dec-react
  labels:
    {{- include "bin2dec.labels" . | nindent 4 }}
    app.kubernetes.io/component: bin2dec-react
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: bin2dec-react
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bin2dec-react
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: bin2dec-react
          image: {{ .Values.frontend.image }}:{{ .Values.tag }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: http
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: http
