apiVersion: v1
kind: Service
metadata:
  name: bin2dec-react
  labels:
    {{- include "bin2dec.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: bin2dec-react
    app.kubernetes.io/instance: {{ .Release.Name }}
