apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "bin2dec.fullname" . }}
  labels:
    {{- include "bin2dec.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
    - http:
        paths:
          - path: /api
            backend:
              serviceName: bin2dec-api
              servicePort: 8080
          - path: /
            backend:
              serviceName: bin2dec-react
              servicePort: 80
